Repository abloom-AOS/MERY_Android, pull requests merged in 2024-03, with the labels that each got.

#5 [Feat/#6] 데이터바인딩 적용
  app/build.gradle.kts
  app/src/main/java/com/abloom/marry/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: 🗝️ Feat, 👍🏻 Merge Needed, 🌱 Simple

#9 [Chore/#8]: 코드 컨벤션 규칙 추가 및 코드에 규칙 적용
  .editorconfig
  .github/ISSUE_TEMPLATE/버그-보고-템플릿.md
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  app/build.gradle.kts
  app/src/androidTest/java/com/abloom/marry/ExampleInstrumentedTest.kt
  app/src/main/java/com/abloom/marry/MainActivity.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/text_styles.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/abloom/marry/ExampleUnitTest.kt
Labels: ⚙️ Chore, 👀 Review Needed, 🌱 Simple

#7 [Feat/#10] 카카오 GlobalApplication 생성 및 초기화
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/marry/MainActivity.kt
  app/src/main/java/com/abloom/marry/MarryApplication.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ⚙️ Chore, 🗝️ Feat, 👀 Review Needed, 🌱 Simple

#12 [Design/#11] 색상 변경
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/marry/MainActivity.kt
  app/src/main/java/com/abloom/marry/MarryApplication.kt
  app/src/main/res/values/colors.xml
Labels: 🎨 Design, 🚨 Emergency, 👀 Review Needed, 🌱 Simple

#15 [Ref/#14] 클래스와 패키지의 이름 변경
  .editorconfig
  app/build.gradle.kts
  app/src/androidTest/java/com/abloom/mery/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/mery/MainActivity.kt
  app/src/main/java/com/abloom/mery/MeryApplication.kt
  app/src/test/java/com/abloom/mery/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 🛠️ Ref, 👀 Review Needed, 🌱 Simple

#18 [Design/#17] 새로운 디자인 시스템 적용
  app/src/main/res/values/colors.xml
Labels: 🎨 Design, 👀 Review Needed, 🌱 Simple

#20 [Ref/#19] 앱 코드 내의 모든 Marry 문자열을 Mery로 변경
  app/src/androidTest/java/com/abloom/mery/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_styles.xml
  app/src/main/res/values/themes.xml
Labels: 🛠️ Ref, 👀 Review Needed, 🌱 Simple

#22 [Bug/#21] 문자열이 겹치지 않게 수정
  app/src/main/res/values/text_styles.xml
Labels: 🐛 Bug, 👀 Review Needed, 🌱 Simple

#25 [Feat/#24] MeryAppBar 구현
  app/build.gradle.kts
  app/src/main/java/com/abloom/mery/presentation/common/util/IntExt.kt
  app/src/main/java/com/abloom/mery/presentation/common/view/MeryAppBar.kt
  app/src/main/res/color/text_button.xml
  app/src/main/res/values/attrs.xml
Labels: 🗝️ Feat, 👀 Review Needed

#16 [Feat/#13] 로그인 화면 구성 및 카카오 로그인 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/mery/HomeActivity.kt
  app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
  app/src/main/res/drawable/kakao_btn.xml
  app/src/main/res/drawable/kakao_logo.xml
  app/src/main/res/drawable/rounded_top_corners.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_login_dialog.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🎨 Design, 📄 Doc, 🗝️ Feat, 👀 Review Needed

#30 [Design/#29] 새 디자인 시스템 적용
  app/src/main/java/com/abloom/mery/MainActivity.kt
  app/src/main/java/com/abloom/mery/presentation/common/view/MeryAppBar.kt
  app/src/main/res/color/text_button.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_login_dialog.xml
  app/src/main/res/values/colors.xml
Labels: 🎨 Design, 🚨 Emergency, 👀 Review Needed, 🌱 Simple

#33 Feature/31 회원가입 Step01 UI 개발
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
  app/src/main/res/drawable/progress_horizontal_custom.xml
  app/src/main/res/drawable/signup_gender_selected.xml
  app/src/main/res/drawable/signup_gender_unselected.xml
  app/src/main/res/layout/fragment_login_dialog.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🗝️ Feat, 👀 Review Needed

#37 [Feat/35] 회원가입 Step02 결혼 날짜 선택 UI 구현
  app/src/main/java/com/abloom/mery/createqnaretest/CreateQnaViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/MarryDateFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
  app/src/main/res/layout/fragment_bride_groom_selection.xml
  app/src/main/res/layout/fragment_marry_date.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/navigation/app.xml
  app/src/main/res/navigation/signup_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🗝️ Feat, 👀 Review Needed, 🌱 Simple

#44 [Feat/#28] 문답 확인 UI 개발
  app/src/main/java/com/abloom/mery/data/repository/FakeQnaRepository.kt
  app/src/main/java/com/abloom/mery/presentation/common/bindingadapter/TextViewBindingAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/common/bindingadapter/ViewBindingAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/QnaFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/QnaViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/ResponseSelectDialog.kt
  app/src/main/res/drawable/bg_all_primary_button_big.xml
  app/src/main/res/drawable/bg_response_select_dialog.xml
  app/src/main/res/drawable/ic_all_close_button.xml
  app/src/main/res/drawable/ic_response_select_dialog_close_button.xml
  app/src/main/res/drawable/img_qna_better_know_response.xml
  app/src/main/res/drawable/img_qna_doing_well_response_result.xml
  app/src/main/res/drawable/img_qna_good_response.xml
  app/src/main/res/drawable/img_qna_lets_find_response.xml
  app/src/main/res/drawable/img_qna_lets_talk_response.xml
  app/src/main/res/drawable/img_qna_lock_response.xml
  app/src/main/res/drawable/img_qna_login_user_response_add.png
  app/src/main/res/drawable/img_qna_login_user_response_indicator.xml
  app/src/main/res/drawable/img_qna_more_find_response_result.xml
  app/src/main/res/drawable/img_qna_more_talk_response_result.xml
  app/src/main/res/drawable/img_qna_waiting_response.xml
  app/src/main/res/font/nps_regular.ttf
  app/src/main/res/layout/dialog_response_select.xml
  app/src/main/res/layout/fragment_qna.xml
  app/src/main/res/navigation/app.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/abloom/domain/qna/model/Qna.kt
  domain/src/main/java/com/abloom/domain/qna/model/UnconnectedQna.kt
Labels: 🗝️ Feat, 👀 Review Needed

#47 [Fix/#46] GetAvailableQuestionsUseCase 수정
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryViewModel.kt
  domain/src/main/java/com/abloom/domain/question/usecase/GetAvailableQuestionsUseCase.kt
Labels: 🐛 Bug, 🚨 Emergency, 👀 Review Needed, 🌱 Simple

#49 [Feat/#45] 프로필 메뉴 UI 개발
  app/src/main/java/com/abloom/mery/data/repository/FakeUserRepository.kt
  app/src/main/java/com/abloom/mery/presentation/common/view/ConfirmDialog.kt
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/LoginUserDescriptionUiState.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/WebViewFromProfileMenuFragment.kt
  app/src/main/res/drawable/bg_confirm_dialog.xml
  app/src/main/res/drawable/bg_profilemenu_marriage_date.xml
  app/src/main/res/drawable/categoryitem_border.xml
  app/src/main/res/drawable/ic_childrenblack.xml
  app/src/main/res/drawable/ic_childrenpurple.xml
  app/src/main/res/drawable/ic_communicationblack.xml
  app/src/main/res/drawable/ic_communicationpurple.xml
  app/src/main/res/drawable/ic_familyblack.xml
  app/src/main/res/drawable/ic_familypurple.xml
  app/src/main/res/drawable/ic_financeblack.xml
  app/src/main/res/drawable/ic_financepurple.xml
  app/src/main/res/drawable/ic_futureblack.xml
  app/src/main/res/drawable/ic_futurepurple.xml
  app/src/main/res/drawable/ic_healthblack.xml
  app/src/main/res/drawable/ic_healthpurple.xml
  app/src/main/res/drawable/ic_lifestyleblack.xml
  app/src/main/res/drawable/ic_lifestylepurple.xml
  app/src/main/res/drawable/ic_pastblack.xml
  app/src/main/res/drawable/ic_pastpurple.xml
  app/src/main/res/drawable/ic_presentblack.xml
  app/src/main/res/drawable/ic_presentpurple.xml
  app/src/main/res/drawable/ic_profilemenu_calender.xml
  app/src/main/res/drawable/ic_profilemenu_go_to_detail.xml
  app/src/main/res/drawable/ic_profilemenu_unconnected_notifier.xml
  app/src/main/res/drawable/ic_sexblack.xml
  app/src/main/res/drawable/ic_sexpurple.xml
  app/src/main/res/drawable/ic_valuesblack.xml
  app/src/main/res/drawable/ic_valuespurple.xml
  app/src/main/res/drawable/ic_weddingblack.xml
  app/src/main/res/drawable/ic_weddingpurple.xml
  app/src/main/res/drawable/img_profilemenu_bride.png
  app/src/main/res/drawable/img_profilemenu_groom.png
  app/src/main/res/drawable/img_profilemenu_not_login_user.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_profile_menu.xml
  app/src/main/res/layout/fragment_web_view_from_profile_menu.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/navigation/app.xml
  app/src/main/res/values/strings.xml
Labels: 🗝️ Feat, Merge Needed

#53 [Design/#52] 로그인 UI 개발
  app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
  app/src/main/res/drawable/apple_btn_background.xml
  app/src/main/res/drawable/apple_logo.xml
  app/src/main/res/drawable/google_btn_background.xml
  app/src/main/res/drawable/google_logo.xml
  app/src/main/res/drawable/kakao_btn_background.xml
  app/src/main/res/layout/fragment_login_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 👀 Review Needed, 🌱 Simple

#42 [Feature/#41] 회원가입 Step3 이름입력 UI 구현
  app/build.gradle.kts
  app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/MarryDateFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
  app/src/main/res/drawable/edit_text_clear_img.xml
  app/src/main/res/drawable/signup_input_name_edit_text.xml
  app/src/main/res/layout/fragment_bride_groom_selection.xml
  app/src/main/res/layout/fragment_input_name.xml
  app/src/main/res/layout/fragment_marry_date.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/navigation/signup_nav_graph.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ⚙️ Chore, 🎨 Design, 🗝️ Feat, 👀 Review Needed

#57 [Feat/#51] 상대방과 연결 기능 개발
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/mery/data/repository/FakeUserRepository.kt
  app/src/main/java/com/abloom/mery/presentation/common/bindingadapter/TextViewBindingAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/common/util/ContextExt.kt
  app/src/main/java/com/abloom/mery/presentation/common/util/ViewExt.kt
  app/src/main/java/com/abloom/mery/presentation/common/view/InfoDialog.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/ConnectEvent.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/ConnectFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/ConnectViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/KakaoShare.kt
  app/src/main/res/drawable-xxxhdpi/img_connect_is_connected.png
  app/src/main/res/drawable/bg_all_dialog.xml
  app/src/main/res/drawable/bg_connect_fiance_invitation_code.xml
  app/src/main/res/drawable/bg_connect_fiance_invitation_code_input_entered.xml
  app/src/main/res/drawable/bg_connect_fiance_invitation_code_input_not_entered.xml
  app/src/main/res/drawable/bg_connect_invitation_code_copy_button.xml
  app/src/main/res/drawable/bg_connect_kakao_share_button.xml
  app/src/main/res/drawable/bg_connect_login_user_invitation_code.xml
  app/src/main/res/drawable/ic_connect_copy.xml
  app/src/main/res/drawable/ic_connect_copy_dark.xml
  app/src/main/res/drawable/ic_connect_is_connect_waiting.xml
  app/src/main/res/drawable/ic_connect_kakao_share.xml
  app/src/main/res/drawable/ic_profilemenu_unconnected_notifier.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/layout/dialog_info.xml
  app/src/main/res/layout/fragment_connect.xml
  app/src/main/res/layout/fragment_profile_menu.xml
  app/src/main/res/values/strings.xml
Labels: 🗝️ Feat, 👀 Review Needed

#60 [Feat/#58] 로그인 기능 연동
  app/src/main/java/com/abloom/mery/HomeActivity.kt
  app/src/main/java/com/abloom/mery/presentation/MainViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/common/EventFlow.kt
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuFragment.kt
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/values/strings.xml
Labels: 🗝️ Feat, 👀 Review Needed
