Repository abloom-AOS/MERY_Android, pull requests merged in 2024-04, with the labels that each got.

#65 [Feat/#50] 회원가입 step04 약관동의화면 UI 구현
  app/src/main/java/com/abloom/mery/presentation/ui/signup/PrivacyConsentFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/webview/WebViewFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/webview/WebViewUrl.kt
  app/src/main/res/drawable/bg_signup_sign_up_button.xml
  app/src/main/res/drawable/check_detail_checked.xml
  app/src/main/res/drawable/check_detail_unchecked.xml
  app/src/main/res/drawable/checkcircle_checked.xml
  app/src/main/res/drawable/checkcircle_unchecked.xml
  app/src/main/res/drawable/consent_checkbox_background.xml
  app/src/main/res/drawable/consent_detail_checkbox_background.xml
  app/src/main/res/layout/fragment_privacy_consent.xml
  app/src/main/res/layout/fragment_web_view.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_styles.xml
Labels: 🎨 Design, 🗝️ Feat, 👀 Review Needed

#68 [Feat/#67] 회원탈퇴 기능 개발
  app/src/main/java/com/abloom/mery/presentation/ui/leave/LeaveFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/leave/LeaveViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuFragment.kt
  app/src/main/res/layout/fragment_leave.xml
  app/src/main/res/navigation/app.xml
  app/src/main/res/values/strings.xml
Labels: 🗝️ Feat, 👀 Review Needed

#62 [Feat/#61] 로그아웃 기능 개발
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/webview/WebViewFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/webview/WebViewUrl.kt
  app/src/main/res/values/strings.xml
Labels: 🗝️ Feat, 👀 Review Needed, 🌱 Simple

#66 [Feat/#63] 세부 프로필 메뉴 UI 개발
  app/build.gradle.kts
  app/src/main/java/com/abloom/mery/presentation/common/bindingadapter/TextViewBindingAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/common/util/IntExt.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/NameChangeDialog.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileDetailMenuDialog.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/marriagedatechange/CalendarDayAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/marriagedatechange/CalendarDayViewHolder.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/marriagedatechange/MarriageDateChangeDialog.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/marriagedatechange/MarriageDateChangeViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/ResponseSelectDialog.kt
  app/src/main/res/drawable/bg_all_dialog_big.xml
  app/src/main/res/drawable/bg_marriagedatechangedialog_selected_date.xml
  app/src/main/res/drawable/bg_namechangedialog_name_input.xml
  app/src/main/res/drawable/ic_marriagedatechangedialog_month_calendar_header_decoration.xml
  app/src/main/res/drawable/ic_marriagedatechangedialog_month_picker_header_decoration.xml
  app/src/main/res/font/sf_pro_display_medium.ttf
  app/src/main/res/font/sf_pro_display_regular.ttf
  app/src/main/res/font/sf_pro_text_semibold.ttf
  app/src/main/res/layout/dialog_marriage_date_change.xml
  app/src/main/res/layout/dialog_name_change.xml
  app/src/main/res/layout/dialog_profile_detail_menu.xml
  app/src/main/res/layout/layout_marriagedatechangedialog_day.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle/libs.versions.toml
Labels: 🗝️ Feat, 👀 Review Needed

#70 [Feat/#69] 스플래시 작업
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/mery/presentation/MainActivity.kt
  app/src/main/res/drawable/ic_splash.xml
  app/src/main/res/drawable/ic_splash_dummy.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 🗝️ Feat, 👀 Review Needed

#76 [Feat/#71] 홈 화면 개발
  app/src/main/java/com/abloom/mery/presentation/common/bindingadapter/RecyclerViewBindingAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/qnasrecyclerview/QnaAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/qnasrecyclerview/QnaDiffUtil.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/qnasrecyclerview/QnaViewHolder.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuFragment.kt
  app/src/main/res/drawable/bg_homeqna_category_tag.xml
  app/src/main/res/drawable/bg_homeqna_complete_tag.xml
  app/src/main/res/drawable/bg_homeqna_request_tag.xml
  app/src/main/res/drawable/bg_homeqna_status_tag.xml
  app/src/main/res/drawable/ic_all_unconnected_notifier.xml
  app/src/main/res/drawable/ic_home_create_qna_button.xml
  app/src/main/res/drawable/ic_splash.xml
  app/src/main/res/drawable/img_all_bride.png
  app/src/main/res/drawable/img_all_groom.png
  app/src/main/res/drawable/img_mery_logo_flat.xml
  app/src/main/res/drawable/img_profilemenu_bride.png
  app/src/main/res/drawable/img_profilemenu_groom.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile_menu.xml
  app/src/main/res/layout/item_home_qna.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 🗝️ Feat, 👀 Review Needed

#75 [Chore/#73]: 파이어베이스 gradle 추가
  .gitignore
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ⚙️ Chore, 👀 Review Needed, 🌱 Simple

#79 [Bug/#78]: 홈화면 로그인 다이얼로그 재생성 버그 수정
  .gitignore
  app/.gitignore
  app/src/main/java/com/abloom/mery/presentation/MainActivity.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/splash/SplashFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/navigation/app.xml
Labels: 🐛 Bug, 🚨 Emergency, 👀 Review Needed, 🌱 Simple

#85 [Feat/#80] 가입화면 이동 로직 변경
  app/build.gradle.kts
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeEvent.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginEvent.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/AuthenticationArgs.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/PrivacyConsentFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpViewModel.kt
  app/src/main/res/navigation/app.xml
  domain/src/main/java/com/abloom/domain/user/model/Authentication.kt
Labels: 🗝️ Feat, 👀 Review Needed

#82 [Design/#81]: 애플 로그인 버튼 제거
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
  app/src/main/res/drawable/apple_btn_background.xml
  app/src/main/res/drawable/apple_logo.xml
  app/src/main/res/drawable/bg_all_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_login_dialog.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 🎨 Design, 🚨 Emergency, 👀 Review Needed, 🌱 Simple

#94 [Fix/#93] repeatOnStarted 함수 수정
  app/src/main/java/com/abloom/mery/presentation/MainActivity.kt
  app/src/main/java/com/abloom/mery/presentation/common/bindingadapter/RecyclerViewBindingAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/common/extension/ContextExt.kt
  app/src/main/java/com/abloom/mery/presentation/common/extension/FragmentExt.kt
  app/src/main/java/com/abloom/mery/presentation/common/extension/IntExt.kt
  app/src/main/java/com/abloom/mery/presentation/common/extension/ViewExt.kt
  app/src/main/java/com/abloom/mery/presentation/common/view/ConfirmDialog.kt
  app/src/main/java/com/abloom/mery/presentation/common/view/InfoDialog.kt
  app/src/main/java/com/abloom/mery/presentation/common/view/MeryAppBar.kt
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/ConnectFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/KakaoShare.kt
  app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/dialog/NameChangeDialog.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/dialog/marriagedatechange/MarriageDateChangeDialog.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/QnaFragment.kt
Labels: 🐛 Bug, 🚨 Emergency, 👀 Review Needed

#96 [Feat/#95] 메리 아이콘 로고 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/mery/AlarmReceiver.kt
  app/src/main/java/com/abloom/mery/MeryFirebaseMessagingService.kt
  app/src/main/mery_app_icon-playstore.png
  app/src/main/res/drawable/ic_notification.png
  app/src/main/res/drawable/mery_app_logo.xml
  app/src/main/res/mipmap-anydpi-v26/mery_app_icon.xml
  app/src/main/res/mipmap-anydpi-v26/mery_app_icon_round.xml
  app/src/main/res/mipmap-hdpi/mery_app_icon.webp
  app/src/main/res/mipmap-hdpi/mery_app_icon_foreground.webp
  app/src/main/res/mipmap-hdpi/mery_app_icon_round.webp
  app/src/main/res/mipmap-mdpi/mery_app_icon.webp
  app/src/main/res/mipmap-mdpi/mery_app_icon_foreground.webp
  app/src/main/res/mipmap-mdpi/mery_app_icon_round.webp
  app/src/main/res/mipmap-xhdpi/mery_app_icon.webp
  app/src/main/res/mipmap-xhdpi/mery_app_icon_foreground.webp
  app/src/main/res/mipmap-xhdpi/mery_app_icon_round.webp
  app/src/main/res/mipmap-xxhdpi/mery_app_icon.webp
  app/src/main/res/mipmap-xxhdpi/mery_app_icon_foreground.webp
  app/src/main/res/mipmap-xxhdpi/mery_app_icon_round.webp
  app/src/main/res/mipmap-xxxhdpi/mery_app_icon.webp
  app/src/main/res/mipmap-xxxhdpi/mery_app_icon_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/mery_app_icon_round.webp
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🗝️ Feat, 👀 Review Needed, 🌱 Simple

#99 [Feat/#98] 구성 변경 대응
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/mery/presentation/MainActivity.kt
Labels: 🚨 Emergency, 🗝️ Feat, 👀 Review Needed, 🌱 Simple

#100 [Bug/#97] DatePicker 년 일 문구 보이게 수정
  app/src/main/java/com/abloom/mery/presentation/ui/signup/MarryDateFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/datepicker/MeryDatePickerView.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/datepicker/MeryYearWheelAdapter.kt
  app/src/main/res/layout/fragment_marry_date.xml
Labels: 🐛 Bug, 🎨 Design, 🚨 Emergency, 👀 Review Needed, 🌱 Simple

#102 [Bug/#101] 회원가입 이름 입력 단계에서 텍스트가 입력창의 border와 겹쳐 있는 디자인 수정
  app/src/main/res/layout/fragment_bride_groom_selection.xml
  app/src/main/res/layout/fragment_input_name.xml
  app/src/main/res/layout/fragment_marry_date.xml
Labels: 🐛 Bug, 🎨 Design, 🚨 Emergency, 👀 Review Needed, 🌱 Simple

#108 [Fix/#107] 안전하게 화면 이동
  app/src/main/java/com/abloom/mery/data/firebase/user/UserFirebaseDataSource.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/ConnectFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/leave/LeaveFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/profilemenu/ProfileMenuFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/QnaFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/PrivacyConsentFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/splash/SplashFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/webview/WebViewFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/writeanswer/WriteAnswerFragment.kt
Labels: 🐛 Bug, 🚨 Emergency, 👀 Review Needed

#110 [Fix/#109] 다이얼로그와 앱바 크기 고정
  app/src/main/java/com/abloom/mery/presentation/MainActivity.kt
  app/src/main/java/com/abloom/mery/presentation/common/extension/IntExt.kt
Labels: 🐛 Bug, 🚨 Emergency, 👀 Review Needed, 🌱 Simple

#115 [Feat/#114] 구글 소셜 로그인 연동 시 사용자 이메일 정보 추가
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
Labels: 🚨 Emergency, 🗝️ Feat, 👀 Review Needed, 🌱 Simple

#116 [Feat/#111] 딥링크 기능 구현
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/abloom/mery/MeryApplication.kt
  app/src/main/java/com/abloom/mery/MeryFirebaseMessagingService.kt
  app/src/main/java/com/abloom/mery/data/firebase/user/UserFirebaseDataSource.kt
  app/src/main/java/com/abloom/mery/data/repository/DefaultUserRepository.kt
  app/src/main/java/com/abloom/mery/presentation/MainActivity.kt
  app/src/main/java/com/abloom/mery/presentation/common/base/NavigationFragment.kt
  app/src/main/java/com/abloom/mery/presentation/notification/MeryNotificationChannel.kt
  app/src/main/java/com/abloom/mery/presentation/notification/Notification.kt
  app/src/main/java/com/abloom/mery/presentation/notification/NotificationHelper.kt
  app/src/main/java/com/abloom/mery/presentation/notification/NotificationReceiver.kt
  app/src/main/java/com/abloom/mery/presentation/notification/TodayQuestionAlarmReceiver.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/QnaFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/writeanswer/WriteAnswerFragment.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/abloom/domain/user/repository/UserRepository.kt
  domain/src/main/java/com/abloom/domain/user/usecase/ConnectWithFianceUseCase.kt
Labels: 🗝️ Feat, 👀 Review Needed

#118 [Feat/#117] 회원 탈퇴 시 답변 삭제
  app/build.gradle.kts
  app/src/main/java/com/abloom/mery/MeryFirebaseMessagingService.kt
  app/src/main/java/com/abloom/mery/data/firebase/qna/QnaFirebaseDataSource.kt
  app/src/main/java/com/abloom/mery/data/firebase/user/UserFirebaseDataSource.kt
  app/src/main/java/com/abloom/mery/data/repository/DefaultQnaRepository.kt
  app/src/main/java/com/abloom/mery/data/repository/DefaultUserRepository.kt
  app/src/main/java/com/abloom/mery/presentation/MainActivity.kt
  app/src/main/java/com/abloom/mery/presentation/notification/Notification.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/QnaFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/QnaViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/writeanswer/WriteAnswerFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/writeanswer/WriteAnswerViewModel.kt
  app/src/main/res/layout/fragment_sign_up.xml
  domain/src/main/java/com/abloom/domain/user/repository/UserRepository.kt
  domain/src/main/java/com/abloom/domain/user/usecase/ConnectWithFianceUseCase.kt
Labels: 🐛 Bug, 🚨 Emergency, 👀 Review Needed

#122 [Chore/#121] : ui 패키지 난독화 제외 설정 룰 적용
  app/build.gradle.kts
  app/proguard-rules.pro
Labels: 📄 Doc, 🚨 Emergency, 👀 Review Needed, 🌱 Simple
