Repository abloom-AOS/MERY_Android, pull requests merged in 2024-06, with the labels that each got.

#128 [Feat/#127] : MixPanel 코드 삽입
  app/build.gradle.kts
  app/src/main/java/com/abloom/mery/MixpanelManager.kt
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/ConnectFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/connect/ConnectViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/QnaFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/qna/ResponseSelectDialog.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/PrivacyConsentFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/datepicker/MeryDatePickerView.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/datepicker/MeryTripleDependentPickerView.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/datepicker/MeryYearWheelAdapter.kt
  app/src/main/java/com/abloom/mery/presentation/ui/writeanswer/WriteAnswerFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/writeanswer/WriteAnswerViewModel.kt
  app/src/main/res/drawable/dark_text_wheel_colors.xml
  app/src/main/res/drawable/mery_text_wheel_highlight_bg.xml
  app/src/main/res/layout/dark_wheel_picker_item.xml
  app/src/main/res/navigation/app.xml
  app/src/main/res/values-night-v8/wheel_color-night-v8.xml
  app/src/main/res/values/wheel_color.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🗝️ Feat, 🛠️ Ref, 👀 Review Needed

#130 [Feat/#129]: 질문제작소 바로가기 팝업추가
  app/src/main/java/com/abloom/mery/presentation/MainViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryViewModel.kt
  app/src/main/java/com/abloom/mery/presentation/ui/signup/MarryDateFragment.kt
  app/src/main/res/drawable/bg_category_popup_dialog.xml
  app/src/main/res/drawable/category_popup_icon_close_btn.xml
  app/src/main/res/drawable/make_question_arrow.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/navigation/app.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🗝️ Feat, 👀 Review Needed

#133 Feat/#131 파이어베이스 코드 kotlin sdk로 변경
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/abloom/mery/data/datastore/DataStoreModule.kt
  app/src/main/java/com/abloom/mery/data/datastore/MeryPreferencesDataSource.kt
  app/src/main/java/com/abloom/mery/data/firebase/Document.kt
  app/src/main/java/com/abloom/mery/data/firebase/FirebaseModule.kt
  app/src/main/java/com/abloom/mery/data/firebase/FirebaseUtil.kt
  app/src/main/java/com/abloom/mery/data/firebase/TimestampConverter.kt
  app/src/main/java/com/abloom/mery/data/firebase/qna/QnaDocument.kt
  app/src/main/java/com/abloom/mery/data/firebase/qna/QnaFirebaseDataSource.kt
  app/src/main/java/com/abloom/mery/data/firebase/question/EssentialQuestionsDocument.kt
  app/src/main/java/com/abloom/mery/data/firebase/question/QuestionDocument.kt
  app/src/main/java/com/abloom/mery/data/firebase/question/QuestionFirebaseDataSource.kt
  app/src/main/java/com/abloom/mery/data/firebase/user/UserDocument.kt
  app/src/main/java/com/abloom/mery/data/firebase/user/UserFirebaseDataSource.kt
  app/src/main/java/com/abloom/mery/data/repository/DefaultQnaRepository.kt
  app/src/main/java/com/abloom/mery/data/repository/DefaultUserRepository.kt
  app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
  gradle/libs.versions.toml
Labels: 🛠️ Ref, 👀 Review Needed

#138 [Bug/#137] 로그인 버그 고침
  app/src/main/java/com/abloom/mery/data/firebase/user/UserDocument.kt
  app/src/main/java/com/abloom/mery/data/firebase/user/UserFirebaseDataSource.kt
  app/src/main/java/com/abloom/mery/data/repository/DefaultUserRepository.kt
Labels: 🐛 Bug, 👀 Review Needed, 🌱 Simple

#140 [Fix/#139] 기존의 회원 삭제 API를 호출하도록 수정
  app/src/main/java/com/abloom/mery/data/firebase/user/UserFirebaseDataSource.kt
Labels: 🐛 Bug, 👀 Review Needed, 🌱 Simple
